### PR TITLE
Crucible Server: Update outdated packages

### PR DESCRIPTION
**Pull request by uqrtj**
To test, check yarn works without error

```
cd server
yarn
```

### CODE REVIEW

**Comment by pipw** [comment]
`$ yarn outdated` still reports **outdated** packages?

**Comment by uqrtj** [comment]
> `$ yarn outdated` still reports **outdated** packages?

image

Added https://elipse-uq.atlassian.net/browse/TEAM24-229 to update mongo dependencies.

UQ-eLIPSE dependencies can't be updated.

**Review by freshc0w — APPROVED** [review]
LGTM

**Review by Mohamad11Dab — APPROVED** [review]
LGTM

**Pull request merged**
